# Use an official openjdk runtime as a parent image
FROM openjdk:11-jdk

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Install python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean;

# Install any needed packages specified in requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Run server.py when the container launches
CMD ["python3", "server.py"]
